export const PATHS = {
    HOME: '/',
    PAGES: {
        MAIN: {
            DOCUMENTATION: '/documentation',
            FORM: '/form',
            TODOS: '/todos',
        },
        COMPONENTS: {
            ACCORDION: '/accordion',
            AVATAR: '/avatar',
            BADGE: '/badge',
            BREADCRUMB: '/breadcrumb',
            BTN: '/button',
            CHECKBOX: '/checkbox',
            DROPDOWN: '/dropdown',
            INPUT: '/input',
            INPUT_PASSWORD: '/input-password',
            LABEL: '/label',
            LOADER: '/loader',
            MODAL: '/modal',
            PROGRESS: '/progress',
            RADIO: '/radio',
            SEPARATOR: '/separator',
            SIMPLE_LINK: '/simple-link',
            SWITCH: '/switch',
            TABS: '/tabs',
            TEXT: '/text',
            TEXTAREA: '/textarea',
            TITLE: '/title',
            TOAST: '/toast',
        },
        STORE: {
            REDUX_TOOLKIT: '/redux-toolkit',
            ZUSTAND: '/zustand',
        },
    },
    NOT_FOUND: '*',
};
