import { IComponentsSection } from '../../types/interfaces/ComponentsSection';
import { NPM_CLASSNAMES_CODE, NPM_FRAMER_MOTION_CODE } from './npm';
import {
    ACCORDION_CODE,
    ACCORDION_CONTENT_CODE,
    ACCORDION_ITEM_CODE,
    ACCORDION_TITLE_CODE,
    ACCORDION_ACTIVE_USAGE_CODE,
    ACCORDION_USAGE_CODE,
    ACCORDION_WRAPPER_CODE,
} from './accordion';
import {
    AVATAR_CODE,
    AVATAR_GROUP_CODE,
    AVATAR_GROUP_USAGE_CODE,
    AVATAR_IMG_CODE,
    AVATAR_LINK_CODE,
    AVATAR_LINK_USAGE_CODE,
    AVATAR_USAGE_CODE,
    AVATAR_WRAPPER_CODE,
} from './avatar';
import { BADGE_CODE, BADGE_USAGE_CODE } from './badge';
import { BTN_CODE, BTN_LINK_CODE, BTN_LINK_USAGE_CODE, BTN_USAGE_CODE, BTN_WRAPPER_CODE } from './btn';
import { CHECKBOX_CODE, CHECKBOX_USAGE_CODE } from './checkbox';
import {
    DROPDOWN_ALIGN_USAGE_CODE,
    DROPDOWN_CODE,
    DROPDOWN_CONTENT_CODE,
    DROPDOWN_POSITION_USAGE_CODE,
    DROPDOWN_TRIGGER_CODE,
    DROPDOWN_USAGE_CODE,
    DROPDOWN_WRAPPER_CODE,
} from './dropdown';
import { INPUT_CODE, INPUT_PASSWORD_CODE, INPUT_PASSWORD_USAGE_CODE, INPUT_USAGE_CODE } from './Input';
import { LABEL_CODE } from './label';
import { LOADER_CODE, LOADER_USAGE_CODE } from './loader';
import {
    MODAL_CLOSE_CODE,
    MODAL_CODE,
    MODAL_CONTENT_CODE,
    MODAL_LAYER_CODE,
    MODAL_TRIGGER_CODE,
    MODAL_USAGE_CODE,
    MODAL_WRAPPER_CODE,
} from './modal';
import { PROGRESS_CODE, PROGRESS_USAGE_CODE } from './progress';
import { RADIO_CODE, RADIO_USAGE_CODE } from './radio';
import { SEPARATOR_CODE, SEPARATOR_USAGE_CODE } from './separator';
import { SIMPLE_LINK_CODE, SIMPLE_LINK_USAGE_CODE } from './simple-link';
import { SWITCH_CODE, SWITCH_USAGE_CODE } from './switch';
import {
    TABS_ACTIVE_USAGE_CODE,
    TABS_CODE,
    TABS_LIST_CODE,
    TABS_PANEL_CODE,
    TABS_PANELS_CODE,
    TABS_TAB_CODE,
    TABS_USAGE_CODE,
    TABS_WRAPPER_CODE,
} from './tabs';
import { TEXT_CODE, TEXT_USAGE_CODE } from './text';
import { TITLE_CODE, TITLE_USAGE_CODE } from './title';

export const COMPONENTS_SECTIONS: IComponentsSection[] = [
    { id: 'code', text: 'Code' },
    { id: 'usage', text: 'Usage' },
];

export {
    NPM_CLASSNAMES_CODE,
    NPM_FRAMER_MOTION_CODE,
    ACCORDION_CODE,
    ACCORDION_WRAPPER_CODE,
    ACCORDION_ITEM_CODE,
    ACCORDION_TITLE_CODE,
    ACCORDION_CONTENT_CODE,
    ACCORDION_USAGE_CODE,
    ACCORDION_ACTIVE_USAGE_CODE,
    AVATAR_CODE,
    AVATAR_WRAPPER_CODE,
    AVATAR_LINK_CODE,
    AVATAR_IMG_CODE,
    AVATAR_GROUP_CODE,
    AVATAR_USAGE_CODE,
    AVATAR_LINK_USAGE_CODE,
    AVATAR_GROUP_USAGE_CODE,
    BADGE_CODE,
    BADGE_USAGE_CODE,
    BTN_CODE,
    BTN_WRAPPER_CODE,
    BTN_LINK_CODE,
    BTN_USAGE_CODE,
    BTN_LINK_USAGE_CODE,
    CHECKBOX_CODE,
    CHECKBOX_USAGE_CODE,
    DROPDOWN_CODE,
    DROPDOWN_WRAPPER_CODE,
    DROPDOWN_TRIGGER_CODE,
    DROPDOWN_CONTENT_CODE,
    DROPDOWN_USAGE_CODE,
    DROPDOWN_POSITION_USAGE_CODE,
    DROPDOWN_ALIGN_USAGE_CODE,
    INPUT_CODE,
    INPUT_PASSWORD_CODE,
    INPUT_USAGE_CODE,
    INPUT_PASSWORD_USAGE_CODE,
    LABEL_CODE,
    LOADER_CODE,
    LOADER_USAGE_CODE,
    MODAL_CODE,
    MODAL_WRAPPER_CODE,
    MODAL_TRIGGER_CODE,
    MODAL_CONTENT_CODE,
    MODAL_LAYER_CODE,
    MODAL_CLOSE_CODE,
    MODAL_USAGE_CODE,
    PROGRESS_CODE,
    PROGRESS_USAGE_CODE,
    RADIO_CODE,
    RADIO_USAGE_CODE,
    SEPARATOR_CODE,
    SEPARATOR_USAGE_CODE,
    SIMPLE_LINK_CODE,
    SIMPLE_LINK_USAGE_CODE,
    SWITCH_CODE,
    SWITCH_USAGE_CODE,
    TABS_CODE,
    TABS_WRAPPER_CODE,
    TABS_LIST_CODE,
    TABS_TAB_CODE,
    TABS_PANELS_CODE,
    TABS_PANEL_CODE,
    TABS_USAGE_CODE,
    TABS_ACTIVE_USAGE_CODE,
    TEXT_CODE,
    TEXT_USAGE_CODE,
    TITLE_CODE,
    TITLE_USAGE_CODE,
};
