import { DocumentationPage } from './DocumentationPage';
import { HomePage } from './HomePage';
import { NotFoundPage } from './NotFoundPage';
import {
    AccordionPage,
    AvatarPage,
    BadgePage,
    BreadcrumbPage,
    BtnPage,
    CheckboxPage,
    DropdownPage,
    InputPage,
    InputPasswordPage,
    LabelPage,
    LoaderPage,
    ModalPage,
    ProgressPage,
    RadioPage,
    SeparatorPage,
    SimpleLinkPage,
    SwitchPage,
    TabsPage,
    TextareaPage,
    TextPage,
    TitlePage,
    ToastPage,
    TooltipPage,
} from './componentsPages';
import { ReactQueryPage, RtkQueryPage } from './dataFetchingPages';
import { YupPage, ZodPage } from './formValidationPages';
import { ReduxToolkitPage, ZustandPage } from './storePages';

export {
    HomePage,
    DocumentationPage,
    NotFoundPage,
    AccordionPage,
    AvatarPage,
    BadgePage,
    BreadcrumbPage,
    BtnPage,
    CheckboxPage,
    DropdownPage,
    InputPage,
    InputPasswordPage,
    LabelPage,
    LoaderPage,
    ModalPage,
    ProgressPage,
    RadioPage,
    SeparatorPage,
    SimpleLinkPage,
    SwitchPage,
    TabsPage,
    TextareaPage,
    TextPage,
    TitlePage,
    ToastPage,
    TooltipPage,
    ReactQueryPage,
    RtkQueryPage,
    YupPage,
    ZodPage,
    ReduxToolkitPage,
    ZustandPage,
};
