import { DocumentationPage } from './DocumentationPage';
import { FormPage } from './FormPage';
import { HomePage } from './HomePage';
import { NotFoundPage } from './NotFoundPage';
import { TodosPage } from './TodosPage';
import {
    AccordionPage,
    AvatarPage,
    BadgePage,
    BreadcrumbPage,
    BtnPage,
    CheckboxPage,
    DropdownPage,
    InputPage,
    InputPasswordPage,
    LabelPage,
    LoaderPage,
    ModalPage,
    ProgressPage,
    RadioPage,
    SeparatorPage,
    SimpleLinkPage,
    SwitchPage,
    TabsPage,
    TextPage,
    TitlePage,
    ToastPage,
} from './componentsPages';
import { ReduxToolkitPage, ZustandPage } from './storePages';

export {
    HomePage,
    DocumentationPage,
    FormPage,
    NotFoundPage,
    TodosPage,
    AccordionPage,
    AvatarPage,
    BadgePage,
    BreadcrumbPage,
    BtnPage,
    CheckboxPage,
    DropdownPage,
    InputPage,
    InputPasswordPage,
    LabelPage,
    LoaderPage,
    ModalPage,
    ProgressPage,
    RadioPage,
    SeparatorPage,
    SimpleLinkPage,
    SwitchPage,
    TabsPage,
    TextPage,
    TitlePage,
    ToastPage,
    ReduxToolkitPage,
    ZustandPage,
};
